
import shortuuid

class DataManager(object):
    """ The manager that handles file I/O for a session.

    Attributes:
        uuid: The uuid of the session, generated by `shortuuid`. This uuid will 
            be used as the saved file name.
    """
    def __init__(self):
        self.uuid = shortuuid.uuid()

