# Uncomment the next line to define a global platform for your project
platform :osx, '10.15'

target 'image_host_client' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for image_host_client
  pod 'Alamofire'

  target 'image_host_clientTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'image_host_clientUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
